### ISSUE TITLE
8 MongoDB

### ISSUE THREAD

**Issue by MateLoncar** [MateLoncar/capstone-project#15]
## Value proposition

As a user of a mapping application,
I want all new markers I create to be saved in a MongoDB Atlas database
in order to be able to retrieve them later and share them with others.

## Description

The mapping application allows users to add markers on a map to indicate points of interest. The user can add a name, description, and location for each marker. The application currently only stores markers locally, meaning that they are not saved if the user closes the application or logs out.

To address this limitation, we want to implement a feature that will allow the user to save all new markers in a MongoDB Atlas database. This will ensure that the markers are persisted and can be accessed by the user at a later time.

## Acceptance criteria

 -[ ] When the user creates a new marker, it should be automatically saved in the MongoDB Atlas database.
 -[ ] The database should store the name, description, and location of each marker.
 -[ ] The user should be able to view all saved markers in the application, even after closing and reopening the application.
 -[ ] If the user edits an existing marker, the changes should be reflected in the database.

## Tasks

  -[ ] Set up a MongoDB Atlas account and create a database for storing markers.
  -[ ] Modify the application's code to connect to the MongoDB Atlas database.
  -[ ] Update the marker creation process to save new markers to the database.
  -[ ] Implement a way to retrieve markers from the database and display them in the application.
 -[ ] Add error handling to the database operations to handle network issues and other errors.
  -[ ] Update the application's user interface to indicate which markers have been saved to the database and which ones have not.

Size: XL

**Comment by mbosselmann** [comment]
Hi Mate,
great job! 👍 As far as I understand your user story, you want to solve two CRUD operations (READ and CREATE) in one user story or?
Then you should separate this user story into two as every CRUD operation resembles one feature that is complete in itself.

The last task ("Update the application's user interface to indicate which markers have been saved to the database and which ones have not.") could also be a new user story as this is a new frontend feature that you want to implement. 🤔 

I hope this does help and feel free to ask if you have questions. :)

**Comment by MateLoncar** [comment]
thanks for your review, I will try to make 2 US and make it easier. :)
