### ISSUE TITLE
9 Attractions

### ISSUE THREAD

**Issue by MateLoncar** [MateLoncar/capstone-project#16]
Title: Integrate API to Display Landmarks on Map

Value proposition:
As a developer of a mapping application, I want to integrate an API to display mountains and famous statues on the map, so that users can easily add these landmarks to their maps and enhance the visual appeal of the application.

Description:
The current version of the mapping application only allows users to add markers to the map. To improve the user experience and provide additional context, we want to integrate an API that provides access to a database of mountains and famous statues around the world. This will allow users to search for and select a specific landmark, which will be displayed on the map as an icon or image.

Acceptance Criteria:

- [ ] Users should be able to search for landmarks by name using the API.
- [ ] The API should return a list of matching results, along with information about each landmark (e.g. location, name, description, image URL).
- [ ] Users should be able to select a landmark from the list and add it to their map, where it will be displayed as an icon or image.
- [ ] The application should handle errors gracefully and display appropriate messages if the API is unavailable or returns an error.

Tasks:

- [ ] Research available APIs for accessing information about mountains and famous statues.
- [ ] Choose an API that meets the requirements of the user story and integrate it into the application.
- [ ] Modify the application's code to allow users to search for and select landmarks using the API.
- [ ] Implement the display of landmarks on the map as icons or images.
- [ ] Test the new functionality thoroughly to ensure it is working as expected.

Size: XL

**Comment by JessicaLoers** [comment]
**Well done, Mate** ✌️

I am a bit confused of this User Story. To place a visual representation (icon) of a mountain or statue on the map, you don't necessarily need an API. 
If you want to use an API to display, for example, many different attractions and information on the map, it is a User Story that should be written more from the developer's view. 🤷‍♀️

 ## Value proposition
>I want to be able to add mountains or famous statues to my map using an API,

As a user, I'm not really interested in where the info come from. Probably I don't even know what an API is. 

>in order to enhance the visual appeal of the map and provide additional context for users.

Is that really THE value. Using an external API or database also has the advantage, for example, that new attractions can be added. Okay, with a mountain this is perhaps rather rarely the case 😁, but it does happen in other attractions like Theme Parks. 

I think it will help you the most in your process and in your planning if you invest some brainpower in this user story again. 😬

**Comment by MateLoncar** [comment]
thanks for your Feedback,i hope i fixed it now :)

**Comment by CJAkkuec** [comment]
Hey there! 👋 

I'm a little unsure why your user story has two different titles?

> 9 Attractions #16

> Title: Integrate API to Display Landmarks on Map

---

>  Choose an API that meets the requirements of the user story and integrate it into the application.

The way this user story was written, this would be a developer story.

---

>  Users should be able to search for landmarks by name using the API.

>  Modify the application's code to allow users to search for and select landmarks using the API.

> Implement the display of landmarks on the map as icons or images.

Displaying the attractions, being able to search for them and selecting them (displaying a detailed view?) would be at least three different user stories. I think this feature needs to be handled differently entirely, and I'm not sure if it's enough to just fix this developer story.

I think I'd start with a developer story (API Research + Implementation), and move on with several user stories (Attraction Search, Display Attraction Result/Add Marker, Display Attraction Details in a Modal ...).

**Comment by MateLoncar** [comment]
Hi Cj, I am not so sure what I can do in 3 user stories because I have found one cool api which when I implemented will give me all features. If you have couple of minutes to explain me I would appreciate it
